# AutoFarmRegions Configuration

# List of enabled WorldGuard regions where automatic farming will work
enabled-regions: []

# Auto-replant settings
auto-replant:
  # Whether to automatically replant crops when harvested
  enabled: true
  # Whether to add drops directly to inventory
  add-to-inventory: true
  # Whether to drop items on the ground if inventory is full
  drop-if-full: false
  # Inventory full notification settings
  inventory-full-notification:
    # Show a title when inventory is full
    show-title: false
    # Show action bar when inventory is full
    show-action-bar: true
    # Duration of title in ticks (20 ticks = 1 second)
    title-duration: 40

# Crop growth settings
growth:
  # Whether to enable growth in regions
  enabled: true
  # How often to start a new growth chain (in seconds)
  interval: 60
  # How long to wait between each crop in the chain (in ticks, 20 ticks = 1 second)
  chain-delay: 2
  # Whether to show particles when crops grow
  show-particles: true
  # Which particle to show when crops grow
  particle: VILLAGER_HAPPY

# Crop protection settings
protection:
  # Whether to prevent breaking immature crops
  prevent-immature-break: true
  # Whether to show a message when breaking immature crops
  show-immature-message: false
  # Whether to allow breaking crops with specific tools
  require-tools: false
  # List of tools that can break crops (if require-tools is true)
  allowed-tools:
  - WOODEN_HOE
  - STONE_HOE
  - IRON_HOE
  - GOLDEN_HOE
  - DIAMOND_HOE
  - NETHERITE_HOE 