# AutoFarmRegions Configuration
# Version: 1.1
# Support: https://discord.primalmc.fun
#
# This plugin automates farming tasks within WorldGuard regions.
# For help and support, join our Discord server: https://discord.primalmc.fun

# List of WorldGuard region names where auto-farming is enabled
# Example: enabled-regions: [farm1, farm2, wheat-farm]
enabled-regions: []

# Auto-replant settings
auto-replant:
  # Enable or disable automatic replanting of crops
  enabled: true
  
  # If true, crop drops will be added directly to the player's inventory
  # If false, drops will be dropped on the ground
  add-to-inventory: true
  
  # If true and inventory is full, drops will be dropped on the ground
  # If false and inventory is full, drops will be lost
  drop-if-full: false
  
  # Settings for inventory full notifications
  inventory-full-notification:
    # Show a title message when inventory is full
    show-title: false
    
    # Show an action bar message when inventory is full
    show-action-bar: true
    
    # Duration of the title message in ticks (20 ticks = 1 second)
    title-duration: 40

# Automatic crop growth settings
growth:
  # Enable or disable automatic crop growth
  enabled: true
  
  # Time in seconds for crops to grow to maturity
  interval: 60
  
  # Show particle effects when crops grow
  show-particles: true
  
  # Particle type to show when crops grow
  # Available particles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  particle: VILLAGER_HAPPY

# Crop protection settings
protection:
  # Prevent players from breaking immature crops
  prevent-immature-break: true
  
  # Show a message when players try to break immature crops
  show-immature-message: false
  
  # Require specific tools to break crops
  require-tools: false
  
  # List of tools that can be used to break crops
  # Only used if require-tools is true
  allowed-tools:
    - WOODEN_HOE
    - STONE_HOE
    - IRON_HOE
    - GOLDEN_HOE
    - DIAMOND_HOE
    - NETHERITE_HOE 