name: AutoFarmRegions
version: '${project.version}'
main: com.example.autofarmregions.AutoFarmRegions
api-version: '1.19'
depend: [WorldGuard]
description: |
  Automates farming tasks within WorldGuard regions.
  Support: https://discord.primalmc.fun

commands:
  autofarmregions:
    description: Main command for AutoFarmRegions
    usage: /<command> [reload|addregion|listregions]
    aliases: [afr]
    permission: autofarmregions.admin

permissions:
  autofarmregions.admin:
    description: Allows access to all AutoFarmRegions admin commands
    default: op
  autofarmregions.use:
    description: Allows players to use auto-farming features
    default: true 